CC = gcc
49_1_FILE = 49_1

all:run

run:
	$(CC) -c $(49_1_FILE).c
	$(CC) -o $(49_1_FILE) $(49_1_FILE).o
	clear

	# instruction for HW9
	# 1.
	# 	./mycp <source> <destination>

clean:
	rm -f $(49_1_FILE) $(49_1_FILE).o
